# Created using wingetcreate
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Loomd.Loom
PackageVersion: 0.7.12
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/loomd/loom/releases/download/v0.7.12/Loom_0.7.12_x64-setup.exe
    InstallerSha256: a6cb3e1abba9a20aaa9998dec071ae63b9f6acb83ab141d3928082999bb7cd0c
    ProductCode: com.loom.app
AppsAndFeaturesEntries:
  - DisplayName: Loom
    Publisher: Loomd
    ProductCode: com.loom.app
ManifestType: installer
ManifestVersion: 1.9.0
